### ISSUE TITLE
Enhancement - Way to import Postman collection

### ISSUE THREAD

**Issue by samlach2222** [moztl/Restful-Api-Tool#13]
It's possible to export to Postman collection, but it will be very useful if importing Postman Collection will be possible

**Comment by moztl** [comment]
Thank you for your feedback. The Postman import feature will be added in future versions.

**Comment by moztl** [comment]
The new version v0.2.26 already supports import from Postman. Under market review or Local installation package: https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.26
