### ISSUE TITLE
希望能在API树中显示每个文件和接口的注释

### ISSUE THREAD

**Issue by lidelu** [moztl/Restful-Api-Tool#14]
希望能在API树中显示每个文件和接口的注释。
比如下面这样的代码，希望能解析到类注释“测试相关接口”、接口注释“获取配置”并显示在树中。
/**
 * 测试相关接口
 */
@RestController
@RequestMapping("/test")
public class TestController {
    /**
     * 获取配置
     */
    @GetMapping("/param/{id}")
    public List<Param> bookParam(@PathVariable Long id) {
        //....
    }
}
参考另一个插件截图
![comment](https://github.com/user-attachments/assets/4d62eaba-fb90-40e8-83bd-2edd206f48d9)

**Comment by moztl** [comment]
感谢反馈，该功能将会在下一个版本中，提供相应的选择功能键。

**Comment by moztl** [comment]
最新版本 v0.2.29 已支持，IDEA插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.29
