### ISSUE TITLE
建议增加动态参数生成

### ISSUE THREAD

**Issue by jay763190097** [moztl/Restful-Api-Tool#15]
像postman一样支持动态uuid生成{{$guid}}

**Comment by moztl** [comment]
感谢反馈，该功能将会在下一个版本中加入。

**Comment by moztl** [comment]
最新版本 v0.2.29 已支持，IDEA插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.29
