### ISSUE TITLE
建议在Controller类上新增 Copy Full URL, Copy Path, Copy as cURL 的功能

### ISSUE THREAD

**Issue by MxJ24** [moztl/Restful-Api-Tool#18]
建议在Controller类上新增 Copy Full URL, Copy Path, Copy as cURL 的功能

**Comment by moztl** [comment]
感谢反馈，针对需求如下：
1. Copy Full URL / Copy Path，前期版本支持，目前已移除，后续考虑重新增加。
2. Copy as cURL 功能详见：https://restful-api-tool.ltfa.top/zh/guide/Functions/CUrl_Export.html

**Comment by moztl** [comment]
之前记错了，Copy Full URL / Copy Path 功能并未移除。
Apis 树中右键对应 Controller 方法，即可呼出功能菜单。

<img width="377" alt="image" src="https://github.com/user-attachments/assets/c1f1b877-4d40-4559-bc8c-528a793a34f2">

**Comment by MxJ24** [comment]
这个能直接在 Controller 方法上点击右键，加这这两个么。类似这样的
![image](https://github.com/user-attachments/assets/b10e6b4d-5a3e-4626-a244-13471ff73916)

**Comment by moztl** [comment]
记起来了，移除的是这里的功能，保留了Api树里的功能。

**Comment by moztl** [comment]
最新版本 v0.2.29 已支持，IDEA插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.29
