### ISSUE TITLE
序列化JSON某些数据类型不对

### ISSUE THREAD

**Issue by MxJ24** [moztl/Restful-Api-Tool#19]
![image](https://github.com/user-attachments/assets/6e49fef1-0db7-4342-80b9-38fd1f690112)
1、import org.bson.types.ObjectId; 这个类型应该序列化成 String
2、enum 类应该根据其value类型序列化

截图的那个类应该序列化成
{
  "classesId": "",
  "userId": "",
  "actionType": 1,
  "osType": 1
}

其中 AccClassesAction 和 OsType 都是枚举类

**Comment by moztl** [comment]
感谢反馈，目前仅做了基础类型解析。后期有时间会考虑扩展。
