### ISSUE TITLE
Header里面仍不支持动态参数生成

### ISSUE THREAD

**Issue by jay763190097** [moztl/Restful-Api-Tool#22]
两个需求，

1. Header支持动态参数生成，因为我们有个traceId放在header里面
2. 保存的请求的时候，能否把header等信息也保存，目前我提交代码后，另一个idea打开，可以从文件里面加载请求信息，但是header没有，不知道是没保存还是没有映射

**Comment by moztl** [comment]
感谢反馈！
1. 目前插件仅支持 Params、Body_form-data、Body_x-www、Body_raw 支持动态参数生成。后续版本考虑增加 Authorization(单个/全局）、Headers（单个/全局）的支持。
2. 保存的请求，除 Response、Console 的数据外，均已存储。可以进行如下检查：
2.1 检查是否是存在同名请求搞混的情况
2.2 检查请求接口的存储信息是否通过代码同步工具同步完成（工程文件下的 .RestfulApiTool 文件夹内容）
2.3 全局配置、环境变量数据仅存在于本机
2.4 或者提供一下具体的复现

**Comment by jay763190097** [comment]
为什么全局配置、环境变量数据仅存在于本机呢？
我的header就是用的全局配置。

**Comment by moztl** [comment]
全局配置、环境变量数据均偏向于个人，设置好之后修改频率偏低。所以不在同步范围内。

**Comment by jay763190097** [comment]
其实不是哦，比如公司有sit和uat环境，某个服务的地址，大家都是一样的。除了自己本地的dev，本地dev其实也基本差不多，都是localhost:8080。postman也是有环境的概念，并且可以导出

**Comment by moztl** [comment]
v0.2.32 已支持 Headers (单个/全局) 动态参数生成。插件市场审核中，本地安装：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.32

**Comment by jay763190097** [comment]
@moztl 感谢大佬，我现在每天都在用它。

**Comment by jay763190097** [comment]
@moztl 能发布一个2023.2的兼容版本吗？公司用的还是旧版的Idea

**Comment by moztl** [comment]
旧版已支持到 2.32。插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.32

**Comment by jay763190097** [comment]
@moztl 感谢！
