### ISSUE TITLE
复制接口地址 操作可以支持一下功能么

### ISSUE THREAD

**Issue by 183461yph** [moztl/Restful-Api-Tool#23]
有环境配置的时候，复制接口地址  操作时，完整的url能使用环境配置的域名和端口么，现在默认都是http://localhost:8080
![image](https://github.com/user-attachments/assets/9103b819-9269-45a9-bc2a-38d13a9eceb2)

**Comment by moztl** [comment]
感谢反馈！
1. 该功能在后续版本会进行优化。
2. 目前版本若想要复制完整的地址，可以使用下图中的 export curl
<img width="423" alt="image" src="https://github.com/user-attachments/assets/86acd791-ef33-4fea-8a51-972f337d31ee">

**Comment by 183461yph** [comment]
> 感谢反馈！
> 
> 1. 该功能在后续版本会进行优化。
> 2. 目前版本若想要复制完整的地址，可以使用下图中的 export curl
> 
> <img alt="image" width="423" src="https://private-user-images.githubusercontent.com/99789152/359742327-86acd791-ef33-4fea-8a51-972f337d31ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTM2ODUsIm5iZiI6MTcyNDIxMzM4NSwicGF0aCI6Ii85OTc4OTE1Mi8zNTk3NDIzMjctODZhY2Q3OTEtZWYzMy00ZmVhLThhNTEtOTcyZjMzN2QzMWVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDA0MDk0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MDNkYjQzOTU2NDc5ZGNmMTlhMGM5MzA3NzAyMmE5ZDUyY2VhNmVlZDMyMjk2YmJhMzdjNDBkYThlOWU3YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r1jJlh9dKN7WobVPSeKChDd2xEo_RuZuJ7_yFIjFQHU">

OK，感谢大佬

**Comment by moztl** [comment]
v0.2.32 已支持 Copy Full Path 选用环境配置（该版本需在面板中选中对应的环境配置 Info）。插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.32

**Comment by 183461yph** [comment]
> v0.2.32 已支持 Copy Full Path 选用环境配置（该版本需在面板中选中对应的环境配置 Info）。插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.32

哇，神速的更新，感谢大佬
