### ISSUE TITLE
最新加的动态参数有bug

### ISSUE THREAD

**Issue by jay763190097** [moztl/Restful-Api-Tool#24]
在body里面我使用两个{{$guid}}想要生成两个uuid，但是结果这两个生成的一模一样。
另外我还是向要postman的动态参数对齐，就用一样的占位符，postman里面有生成时间的，最新加的，没有这些。其他参数名似乎有区别。

**Comment by moztl** [comment]
感谢反馈，问题将会在后续版本中进行修复。
- 当前仅预设 {{$guid}}、{{$randomEmail}}、{{$randomPhone}}、{{$randomInt}}，后续会更新更多的预设。
- 其中 {{$randomPhone}} 因中国号码的特殊性，属于插件额外新增，在 Postman 中不存在。
- 当前占位符均支持导出到 Postman。

**Comment by jay763190097** [comment]
@moztl 可以支持下生成当前时间的，有iso标准格式和时间戳

**Comment by jay763190097** [comment]
@moztl 下个版本啥时候发布呀

**Comment by moztl** [comment]
@jay763190097 10.1之前会有一版

**Comment by moztl** [comment]
v0.2.33 已修复以上问题。插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.33
