### ISSUE TITLE
api搜索优化

### ISSUE THREAD

**Issue by zwj600800** [moztl/Restful-Api-Tool#25]
搜索api时，如果是@RequestMapping(value = "/userss/password", method = RequestMethod.PUT)这种无法识别是put请求
![image](https://github.com/user-attachments/assets/0c15e12b-6d83-41ef-b81d-e693678f3cf1)

**Comment by moztl** [comment]
感谢反馈，改细节将会在后续版本进行优化。

**Comment by moztl** [comment]
v0.2.33 已优化该细节。插件市场审核中，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.33
