### ISSUE TITLE
响应值解析BUG反馈

### ISSUE THREAD

**Issue by chomue** [moztl/Restful-Api-Tool#3]
你好，在使用该插件过程中发现响应值解析存在两个小BUG：
 1. 当响应值为JSON数组时，报错“A JSONObject text must begin with '{' at 1 [character 2 line 1]”；
 2. 当接口响应值为空时，“String index out of range: 0”。

**Comment by moztl** [comment]
感谢反馈，这边尽快修复

**Comment by moztl** [comment]
最新版本已修复，IDEA插件市场还在审核，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.11
