### ISSUE TITLE
存储文件及环境配置优化建议

### ISSUE THREAD

**Issue by chomue** [moztl/Restful-Api-Tool#6]
你好，在使用过程中有一些建议，供作者参考。
1. 目前插件的存储文件是在项目文件下的.RestfulApiTool目录，建议迁移至.idea目录下。理由：在公司开发中代码一般需提交至git，这种与开发者有关的文件应尽可能屏蔽。.idea目录及其下属文件正常情况下会配置在gitignore，无需单独配置，此时插件文件对团队成员不可见。
2. 目前环境配置分为三级：环境、项目、基础信息，建议精简为1级。理由：在idea开发中，不同项目会新建项目文件。同一项目下不会有过多的环境配置。
3. 最最最重要！！！在插件升级等其他情况下会存在配置信息丢失问题，需要重新填写环境配置等信息太多麻烦，希望优化。（插件升级一定会触发信息丢失，其他情况不确定是什么原因。总之经常丢失配置）。

**Comment by moztl** [comment]
感谢反馈，针对所有问题：
1. 新增.RestfulApiTool目录（是在v0.1.4/v0.2.10新增<Saved Requests>功能之后新增的，该目录下仅记录保存的请求信息）。本意是考虑团队开发可以借此共同维护保存的请求信息，减少重新构建请求模板参数的操作，也可为团队后来者提供构建建议。若不考虑团队共享，可将此目录添加至gitignore。
2. 这个建议我后面看看方不方便改成系统配置，自行选择是否存在多级配置。分级本意是为了单个项目不同环境的配置，有些项目同一环境下可能存在多种配置。大部分开发情况下确实不需要这么细分。
3. 配置丢失的问题，检查一下.idea目录下相关的RestfulApiTool-*.xml是否被清理。升级必触发这个问题我排查一下。

**Comment by moztl** [comment]
新版本 v0.1.8/0.2.15 已修复问题点3，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.15

针对问题点3，此次更新依旧会导致旧配置读取失败，若不想手动重新配置，可在.idea目录以及.RestfulApiTool目录下找到RestfulApiTool-*.xml相关文件，并改写图片中option的name值为cache，重启IDEA即可。（注意：在未手动改写前，操作相关功能，将会自动覆盖旧数据）
<img width="310" alt="截屏2024-01-05 21 21 33" src="https://github.com/moztl/Restful-Api-Tool/assets/99789152/b0526358-49d5-44e6-b181-9a96dcc0eeb8">

针对建议点2，系统配置中新增高级环境层级开关（默认开启高级环境层级），如下图，取消该选项，将会切换为简单环境层级。
![11](https://github.com/moztl/Restful-Api-Tool/assets/99789152/4b472427-9519-45fb-bab6-20a70de6afcc)

**Comment by chomue** [comment]
优秀！！！感谢大佬

**Comment by chomue** [comment]
基本设置中”是否开启高级环境级别“选项，在IDEA重启后会失效，需要重新设置。环境配置记录还在，但又会变为3级环境。

**Comment by moztl** [comment]
感谢反馈，系统配置确实存在重启失效的问题，这边尽快修复。

**Comment by moztl** [comment]
新版本 v0.1.9/0.2.16 已修复，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.16
