### ISSUE TITLE
请求好像不支持auth2的验证

### ISSUE THREAD

**Issue by dxcomeon** [moztl/Restful-Api-Tool#7]
请求好像不支持auth2的验证

**Comment by moztl** [comment]
感谢反馈，插件目前确实还没有添加Postman中的Authorization功能块，已添加至开发计划。届时可以查看插件右上角 Version Info 功能，里面罗列了所有开发计划，以及各个功能所支持的版本。

**Comment by moztl** [comment]
最新版本 v0.2.18 已支持部分 Authorization。 支持 `No Auth`、`Basic Auth`、`Bearer Token`
