### ISSUE TITLE
可以新增自定义的mapping注解吗

### ISSUE THREAD

**Issue by sai-guo** [moztl/Restful-Api-Tool#9]
项目上用的@xxxMapping有对spring原生的注解进行扩展，能否支持这个功能呢

**Comment by moztl** [comment]
感谢反馈，这个我看一下。


------------------ 原始邮件 ------------------
发件人: sai-人: moztl/Api<Tool<subscribed@主题: Re: [moztl/Tool] 增自定义的mapping注解吗 (Issue #9)





 
***@***.***有对spring原生的注解进行扩展，能否支持这个功能呢

**Comment by moztl** [comment]
新版本 v0.2.21 已支持基于 @RequestMapping 的自定义注解，本地安装包：https://github.com/moztl/Restful-Api-Tool/releases/tag/v0.2.21
